---
env:
  # this is production
  DB_USER: "darkened_admin"
  DB_PASSWORD: "]{M_Bu2HjA4t"
  # this is test on local machine
  # DB_USER: "root"
  # DB_PASSWORD: "root"
  DB_HOST: "localhost"
  DB_NAME: "Darkened_Minds_Tournaments"

deployment:
  tasks:
  - export DEPLOYPATH=/home/darkened/public_html
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp robots.txt $DEPLOYPATH
  - /bin/cp -R admin $DEPLOYPATH
  - /bin/cp -R assets $DEPLOYPATH
  - /bin/cp -R css $DEPLOYPATH
  - /bin/cp -R js $DEPLOYPATH
  - /bin/cp -R database_scripts $DEPLOYPATH
  - /bin/cp -R services $DEPLOYPATH
  - /bin/cp -R pages $DEPLOYPATH

sql_migrations:
  tasks:
    - name: Execute SQL migrations
      run: |
        set -e
        mysql -u $DB_USER -p"$DB_PASSWORD" -h $DB_HOST < database_scripts/create_new_database.sql >> /tmp/sql_migration.log 2>&1
        mysql -u $DB_USER -p"$DB_PASSWORD" -h $DB_HOST < database_scripts/create_functions.sql >> /tmp/sql_migration.log 2>&1