---
deployment:
  tasks:
  - export DEPLOYPATH=/home/darkened/public_html
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp robots.txt $DEPLOYPATH
  - /bin/cp -R admin $DEPLOYPATH
  - /bin/cp -R assets $DEPLOYPATH
  - /bin/cp -R css $DEPLOYPATH
  - /bin/cp -R services $DEPLOYPATH
  - /bin/cp -R pages $DEPLOYPATH